language: java
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/ui/node/"
  - "$TRAVIS_BUILD_DIR/ui/node_modules/"
  
jdk: openjdk8

install: skip

script: "mvn -B -V -P node_install verify"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh success $DISCORD_WEBHOOK_URL
  
after_failure:
  - wget https://raw.githubusercontent.com/DiscordHooks/travis-ci-discord-webhook/master/send.sh
  - chmod +x send.sh
  - ./send.sh failure $DISCORD_WEBHOOK_URL