language: java
sudo: false # faster builds

cache:
  directories:
  - "$HOME/.m2"
  - "$TRAVIS_BUILD_DIR/ui/node/"
  - "$TRAVIS_BUILD_DIR/ui/node_modules/"
  
jdk: openjdk8

before_script:
  - export BINDIR=$(pwd) && curl -H 'Cache-Control:no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install.sh | bash

install: skip

script: "mvn -B -V -P node_install install -DskipTests"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - ([[ -n "$FOSSA_API_KEY" ]]) && (./fossa analyze)
